name: Europe 2016
favicon: null
layout_spectrum: 0.86259
typography_spectrum: 0.8437164
title: Europe2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9e1ed'
    - '#007296'
    - '#413c18'
    - '#629cae'
    - '#616f28'
  brandStrength: 0.8125
  lightness: 0.5451128
  saturation: 0.5290011
  rhythmicContrast: 0.4108485
purpose: []
